language: haskell

env:
  - GHCVER=7.8.4 STACK_YAML=stack-7.8.yaml
  - GHCVER=7.10.2 STACK_YAML=stack.yaml

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar xz -C $HOME/.local/bin
  - chmod a+x $HOME/.local/bin/stack

install:
  - stack setup --no-terminal
  - stack build --no-terminal

script:
  - stack test :argon-test --no-terminal
