language: haskell

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - $HOME/.stack/

before_install:
  # ghc
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  # stack
  - mkdir -p $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar xz -C $HOME/.local/bin
  - chmod a+x $HOME/.local/bin/stack

#addons:
  #apt:
    #packages:
      #- libgmp-dev

matrix:
  include:
  - env: GHCVER=7.8.4 STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
  - env: GHCVER=7.10.1 STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.1

install:
  - stack +RTS -N2 -RTS setup --no-terminal
  - stack +RTS -N2 -RTS build --only-snapshot --no-terminal

script:
  - stack +RTS -N2 -RTS test :argon-test --no-terminal
