language: haskell

env:
  - GHCVER=7.8.4 STACK_YAML=stack-7.8.yaml
  - GHCVER=7.10.2 STACK_YAML=stack.yaml

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - $HOME/.stack/
    - $HOME/stack/

before_install:
  - ./travis-install-stack.sh
  - cd $HOME/rubik/argon

install:
  - stack setup --no-terminal

script:
  - stack test :argon-test --no-terminal --coverage

after_script:
  - STACK_YAML=stack-travis-coveralls.yaml install stack-hpc-coveralls
  - stack-hpc-coveralls argon argon-test
